name: session_manager
description: "A simple and efficient singleton class for managing session data in Flutter applications using the shared_preferences package. This SessionManager allows you to easily store, retrieve, and manage session data of various types."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
